agent_type: roleplayDoh
data_path: data/characters/Patient Psi CM Dataset.json
data_idx: 0
principles: data/characters/roleplayDohPrinciple.json
api_type: LAB
model_name: gpt-4o
temperature: 0.7
max_tokens: 8192
max_retries: 3
lang: en