agent_type: SimPatient
data_path: data/characters/SimPatient.json
data_idx: 0
api_type: LAB
model_name: gpt-4o
temperature: 0.7
max_tokens: 8192
max_retries: 3
lang: en
continue_last_session: true
conversation_history: data/sessions/SimPatient/session_1.json