agent_type: psyche
output_dir: "data/characters/Psyche MFC.json"
data_idx: 0
api_type: LAB
model_name: gpt-4o
temperature: 0.7
max_tokens: 8192
max_retries: 3
lang: en

diagnosis: "Major Depressive Disorder"
age: 40
sex: "Female"
