agent_type: client
eval_type: conv
api_type: LAB
model_name: gpt-4o
temperature: 0.4
max_tokens: 8192
max_retries: 3
lang: en
input_dir: "data/sessions/patientPsi/session_1.json"
output_dir: "data/evaluations/patientPsi/session_1_turn_conv_eval.json"