defaults:
  - _self_
  - client: patientPsi
  - therapist: CBT
  - evaluator: basic
session:
  lang: en
  reminder_turn_num: 5
  max_turns: 30
  langfuse: False
  recursion_limit: 1000
  output_dir: "data/sessions/patientPsi/session_2.json"